CREATE USER 'rest-api'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT CREATE, DELETE, INSERT, SELECT, UPDATE ON * . * TO 'rest-api'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE microservice;
USE microservice;

CREATE TABLE Login
(
  email VARCHAR(255) NOT NULL PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  hash_salt VARCHAR(255) NOT NULL
);

CREATE TABLE Item
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  quantity INT NOT NULL,
  tags VARCHAR(255) NULL,
  description VARCHAR(255) NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  image_url VARCHAR(255) NOT NULL
);

CREATE TABLE Admin
(
  email VARCHAR(50) NOT NULL PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  hash_salt VARCHAR(255) NOT NULL
);

CREATE TABLE Cart
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  item_id INT NOT NULL,
  quantity INT NOT NULL,

  CONSTRAINT FOREIGN KEY (email) 
    REFERENCES Login(email)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (item_id) 
    REFERENCES Item(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OrderDetail
(
  order_id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  total_amount DECIMAL(15, 2) NOT NULL,
  date DATETIME NOT NULL,
  fulfilled BOOLEAN NOT NULL DEFAULT 0,
  fulfillment_date DATETIME NULL,

  CONSTRAINT FOREIGN KEY (email) 
    REFERENCES Login(email)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OrderItem
(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  order_id VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  quantity INT NOT NULL,
  item_id INT NOT NULL,

  CONSTRAINT FOREIGN KEY (item_id) 
    REFERENCES Item(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY (order_id) 
    REFERENCES OrderDetail(order_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Address
(
  address_id VARCHAR(255) PRIMARY KEY,
  street VARCHAR(50) NOT NULL,
  apt_no VARCHAR(20),
  city VARCHAR(20) NOT NULL,
  state VARCHAR(15) NOT NULL,
  zip_code VARCHAR(15) NOT NULL,
  country VARCHAR(20) NOT NULL,

  CONSTRAINT FOREIGN KEY (address_id) 
    REFERENCES OrderDetail(order_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

